### ISSUE TITLE
Which monitoring do you use now?

### ISSUE THREAD

**Issue by guettli** [simon-weber/opsgrid#1]
I read your article: https://simon.codes/2020/09/20/opsgrid.html

I am in the same situation I run some VPS (mostly for friends). 

I was looking for a simple monitoring solution, too.

**Comment by simon-weber** [comment]
I still use telegraf, but now I send metrics to the free tier of Grafana Cloud. The UI can be kind of painful, but I was already familiar with it from a previous job and the free tier is very generous. Specifically, I use the [new-ish support for prometheus remote-write](https://grafana.com/docs/grafana-cloud/how-do-i/visualize-and-store-influxdb/push-from-telegraf/#pushing-using-the-remote-write-output), so my config looks like:

```
[[outputs.http]]
  url = "https://prometheus-us-central1.grafana.net/api/v1/push"

  username = "${GRAFANA_CLOUD_METRICS_ID}"
  password = "${GRAFANA_CLOUD_API_KEY}"

  data_format = "prometheusremotewrite"

  [outputs.http.headers]
     Content-Type = "application/x-protobuf"
     Content-Encoding = "snappy"
     X-Prometheus-Remote-Write-Version = "0.1.0"
```

It's definitely more complicated to set up, though. Datadog, Nixstats, and New Relic are all simpler, though you may not fit into their free tiers.

**Comment by guettli** [comment]
For me it is not so much about "free tiers". It is more about owning things and running things on-premise. I like open source, even if commercial services are more convenient.

**Comment by simon-weber** [comment]
Ah, ok. I'm less familiar with open-source self-hosted options outside of prometheus and grafana.

**Comment by guettli** [comment]
Thank you for the conversation. All the best.
